### ISSUE TITLE
Feature request: Visualize how "Average PR Open Time" changes over time

### ISSUE THREAD

**Issue by jcgillespie** [jeffpriz/devops-pr-stats#1]
If possible, it would be nice to see a visual of how "average PR open time" changes over time. Are we getting faster or slower in approving PRs? Maybe a graph of some sort?

Thanks for the extension!

**Comment by jeffpriz** [comment]
Hmm, I could see this breaking this PRs down in to 30-day slices and getting the average time in that 30 days... then graphing the times... I might want to use the storage to store those points so I don't have to recalculate the FULL list every time though

**Comment by jcgillespie** [comment]
Yeah. Ultimately, making that time slice configurable would be nice for projects with different levels of "activity".  Changing the configured value would mean a full recalculation though. Storing it seems like a nice optimization.

Perhaps another way to handle would be a "change in tempo in the last 30 days".  That way you'd be calculating a rolling window, (60 days, most recent 30 compared to previous 30), rather than "all of time".

**Comment by jeffpriz** [comment]
No has a chart that shows duration trends.. the interval is set a two weeks, and will show the trend line over up to the last year.. the interval is not configurable right now but will look at this to see how it goes and see if making it configurable in the future makes sense

**Comment by jcgillespie** [comment]
Awesome! Thanks!
