### ISSUE TITLE
Question: Does "Average Time Pull Requests are Open" counts when PR was draft

### ISSUE THREAD

**Issue by nickduch** [jeffpriz/devops-pr-stats#14]
Pretty much what the title says. On the repository PR Stats, the "Average Time Pull Requests" widget displays the average lifespan of a PR, does it include the time in which the PR was in draft?

**Comment by jeffpriz** [comment]
Hey @nickduch that's a great question.  Yes, the time that is used is the created time, and as such it does start the clock when the PR is created, even if it's created as a Draft.

**Comment by nickduch** [comment]
Thanks for the clarification and the quick reply @jeffpriz. Good work by the way :)

**Comment by kwatson1970** [comment]
@jeffpriz - Would it be possible to exclude the time in which the PR was in draft?

**Comment by cosmanovich** [comment]
It would certainly be a nice option to be able to exclude the time in draft. Maybe a setting could be added for this?
Is it something that would be consired adding to this extension?
