### ISSUE TITLE
Error loading the widget

### ISSUE THREAD

**Issue by Yogev-Varonis** [jeffpriz/devops-pr-stats#15]
![image](https://user-images.githubusercontent.com/79836714/120301020-233db000-c2d5-11eb-9e2a-89f179a7a504.png)

**Comment by jeffpriz** [comment]
Just curious if you could provide what version of Azure DevOps Server you're running? I presume you're not on Azure DevOps Services.. I've got another issue opened below for issues on Server, so curious about if you're having the same trouble on the same version

**Comment by Yogev-Varonis** [comment]
Hi Jeff,
My version is: Azure devops server Dev17M153.3
BTW 
When I am using the browser to visit the url, it works.

**Comment by jeffpriz** [comment]
this version of the extension really works with  Azure DevOps Server 2020.1 (Vers 18.181.31425.1) or later
