### ISSUE TITLE
Feature proposal: enhance visibility for big list of contributors and teams

### ISSUE THREAD

**Issue by OxyFlax** [jeffpriz/devops-pr-stats#26]
Currently the extension is good but it becomes quite hard to monitor on projects which have lots of contributors (30-40).
It would be good if we could have something more dynamic in terms of sizing. 
Also for teams approvals, it is counted only if they are added specifically as reviewer of the PRs, it would be nice to be able to identify to which team belongs an approver and revert back his/her approval to the corresponding team for the stats.
Finally, it would be good to have some graphs to get statistics inside the teams and between teams.

Would you agree on such contribution to the project? I could make a PR with such features.

**Comment by jeffpriz** [comment]
Hey, yeah, I love the idea of laying out the graphs etc.. in a better and more dynamic way.  I am not much of a react/ front-end dev.. so help on those things would be huge.  

Might want to understand the teams->user approval person thing a little more though

**Comment by OxyFlax** [comment]
My idea for the teams association is to extract the teams from the project using the CoreRestClient, retrieve the team members using the same and then from the team member, retrieve the counts from the approverDictionary and sum the reviews.

**Comment by jeffpriz** [comment]
Getting to a Team I don't believe is the right direction.. getting to a Group is more appropriate (You can Add a GROUP to the PR approval policy.. if you add a Team's group that's one thing, but those aren't all Teams per se).  Either way, there is no way to know which role a person is reviewing the PR as... as any person can (and often is) a member of multiple teams and groups.  So then you are just guessing at which "role" they are filling for that PR review.. 

In my view the best way to get visibility into what group is making the review is to set that as the reviewer... Organizations who care about that level of reporting should be setting those PR reviews by the group that they want to review... If they are just setting individuals as the reviewer, then they probably don't really care about the visibility of what group is doing the review (and if they do care about that level of reporting they have an actual way to not only report on it but practice and enforce it)

**Comment by OxyFlax** [comment]
Ok I guess our projects are not setup the same, we'll keep our project separate. If you want to have a look I have referenced to this issue. 
I'll open a PR for the small graph display improvement when the list of reviewers is too big!

**Comment by OxyFlax** [comment]
Closing the issue as it's agreed that we have different needs. Pr for the graph layout improvement still open if you want to check and reply there. If anyone interested in my update, it can be checked in the fork referenced above.
