### ISSUE TITLE
PR Stats Graphically broken

### ISSUE THREAD

**Issue by TekuSP** [jeffpriz/devops-pr-stats#3]
![image](https://user-images.githubusercontent.com/13198444/98581838-5c272080-22c2-11eb-9e87-9e620563a2c0.png)
1920x1080 resolution.

**Comment by jeffpriz** [comment]
i see, will work on that spacing here shortly! thanks for the feedback! that's ugly!

**Comment by jeffpriz** [comment]
just published v 1.0.33 that more properly spaces those two graphs so they don't crush each other like that.

**Comment by TekuSP** [comment]
![image](https://user-images.githubusercontent.com/13198444/98604717-812c8b00-22e4-11eb-9009-060f00301dde.png)
Looks better, not best yet.
But at least usable. Thanks.
