### ISSUE TITLE
Repository PR Stats does not loading anything.. 

### ISSUE THREAD

**Issue by cazofeifacr** [jeffpriz/devops-pr-stats#6]
Is not loading ...

![Screen Shot 2021-02-09 at 9 15 43 AM](https://user-images.githubusercontent.com/7798064/107384257-65897a00-6ab7-11eb-9e82-7522963128e8.png)

```
About Azure DevOps Server
Version Dev17.M153.5
```

**Comment by jeffpriz** [comment]
Just curious does the Repo you're on have completed PR's on it? Could you send me anything interesting from the browser developer tools console?

**Comment by schweinsbratn** [comment]
Some in our Azure DevOps Server 2019 setup. I think the problem is because the plugin reloads code from the internet and our server has no internet access. Can this be the reason for not showing anything?
If so, you could build a version that contains all required javascript code inside the plugin?

Thanks

**Comment by jeffpriz** [comment]
> Some in our Azure DevOps Server 2019 setup. I think the problem is because the plugin reloads code from the internet and our server has no internet access. Can this be the reason for not showing anything?
> If so, you could build a version that contains all required javascript code inside the plugin?
> 
> Thanks

The server shouldn't need any access, this is all client-side so the browser you're viewing this on needs to have some access probably, but your Azure DevOps Server itself shouldn't need access.. as long as the client machine can reach the Azure DevOps server...

**Comment by schweinsbratn** [comment]
I was aware that the Javascript functionality would be reloaded in the browser, I just thought that the plugin would also reload something on the server that would not work in our case.
The question remains why the plugin cannot display any data in our setup...

I checked the network output in Firefox and found that, there is a 400 http status code while trying to fetch pullRequests with URL: 
pullRequests?searchCriteria.status=3&searchCriteria.includeLinks=false&searchCriteria.creatorId=&searchCriteria.reviewerId=&searchCriteria.repositoryId=&searchCriteria.sourceRefName=&searchCriteria.targetRefName=&searchCriteria.sourceRepositoryId=&$top=500

When I call this URL manually in Firefox it works and I get a valid response data inside.

**Comment by schweinsbratn** [comment]
Another idea: could it be related to our API version which is: 5.1-preview.1?
Because I had an issue with another plugin which was updated recently, stopped working as this plugin, and the reason for this was a API version change in the plugin.

**Comment by jeffpriz** [comment]
@schweinsbratn  what version of Azure DevOps server are you running?  I don't have an on-prem version to test against, but certainly, likely, that the SDK that I am using has a dependency on a newer set of APIs than what your version has... I may be able to move back the version dependency I have, but I guess I would have to set up a version similar to where your at to see the error

**Comment by schweinsbratn** [comment]
We are running Azure DevOps Server 2019 Update 1.1 (17.153.29522.3) the latest supported API version is 5.1-preview.1.

Thanks in advance for trying to get it working for us :+1:

**Comment by jeffpriz** [comment]
Sorry I haven't had any good updates on this one.. I do have a local copy of Azure DevOps Server 2020.1 (Vers 18.181.31425.1) running in a VM and noticed that the extension was running normally there
