### ISSUE TITLE
Extension failed to load 

### ISSUE THREAD

**Issue by DonetsAndriy** [jeffpriz/devops-pr-stats#7]
I'm trying to use it on the latest on-premise TFS 2018.
For some reason repository set to <none> when I open the extension tab.
When I switch the repository back to one I need, I'm redirected to the 'File' tab.

![image](https://user-images.githubusercontent.com/15216495/109194575-3c006c00-77a2-11eb-9274-a39934cb8087.png)

TFS version Version 16.131.28601.4

**Comment by jeffpriz** [comment]
Thanks for trying this out, but I am sorry,  I really don't think that this will work with that older version of this.  Some of the API and interface objects I use are probably not valid with that version.  The support fort on-prem would need to be the latest Azure DevOps Server versions.

Works with
Azure DevOps Services
Azure DevOps Server
